export {
  setRootFolder as postRootFolder,
  getAllGroups,
  getAllProjects,
  getAllFiles,
  getAllTemplates,
  isGroup,
  isProject,
  isRoot,
  isRootFolder,
  isDirectory,
  isRootDir,
  makeFolder,
  removeFolder,
} from "../workingWithFile";
